services:
  - type: web
    name: booking-backend
    env: node
    region: oregon
    plan: free
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: API_VERSION
        value: v1
      - key: FRONTEND_URL
        value: https://booking-frontend-n6pv.onrender.com
      - key: LOG_LEVEL
        value: info
      - key: BCRYPT_SALT_ROUNDS
        value: 12
      - key: JWT_ACCESS_SECRET
        value: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08
      - key: JWT_REFRESH_SECRET
        value: 1f8a7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a089f86d081
